### ISSUE TITLE
What depth can/should UNTP be considered in a supply chain?

### ISSUE THREAD

**Issue by mxshea** [uncefact/spec-untp#28]
A question on the ‘depth’ to which UNTP will/should be considered into a supply chain.  Here is the example/context.  Would the protocol consider the electronics manufacturing sector as ‘in scope’?  Would/should it be able go down the the component level on a PCB?  Or stay at the ‘finished’ product (whatever that is).

I have had lots of conversations with folks in the Clinical IoT sector, as well as the electronic manufacturer trade association (IPC.org) sector around the need for this level of visibility,  but most of the examples given focus on retail goods, or near finished products in the paper.

**Comment by nissimsan** [comment]
@mxshea, this is excellent. I shared some thoughts on our slack recently which I failed to pass anywhere else. I think they related to this topic: 

Team, there’s a thought which has stuck with me since this week’s CIRPASS conference. I sense a divide in the approach too DPP pre-point of sale and post-point of sale…

Use cases:
Pre-Point of Sale deals with product origin, traceability, certificates, customs-oriented
Post-Point of Sale deals with product future, lifecycle, sensor data capturing, consumer-input

Tech-wise:
Pre-Point of Sale requires verifiability, redaction, trust anchoring
Post-Point of Sale requires immutability

Geographically:
Pre-Point of Sale data is generally foreignly generated
Post-Point of Sale data is generally domestically generated

I don’t know where exactly these thoughts are going… But I just feel like it’s a thread worth pulling.
Maybe - _maybe_ - UNTP is Pre-POS, EU is Post-POS

**Comment by zachzeus** [comment]
I also think there is a simplifying mental model to apply here.  The core of the UNTP is the concept of a Digital Product Passport that is passed at the product level at the time the product is sold. It doesn't matter if the product is a box of rocks, a sub-assemply of a car, or structural steel.  The power comes if supply chain actors choose to share these DPP's.  A key insight is that the global marketplace already shares data associated with shipped products (invoices, shipping data, payments etc).

**Comment by onthebreeze** [comment]
Extensions methodology gives a hint about this.  see #36

**Comment by monkeypants** [comment]
Maybe it's more complicated than that @nissimsan; 
* post/ pre points of sale are relative, all the transformation events in a supply chain have at least one point of sale on both input and output sides. 
* post-point-of-sale imutability? suggest that append-only mutability would be needed in some cases. Consider the discussion in #43, when more evidence to support a claim becomes available, we might want to update the DPP with new evidence. As long as all older versions are discoverable, and deletion is not possible, when might the ability to add new evidence to support existing claims be a problem?

@mxshea I don't see a reason why there would be a limit on the "depth", in theory I think the protocol should extend to anywhere the market demands reified claims about stuff in a supply chain. An electronics BOM is a great example; ESG claims about tantalum in capacitors on a particular component, rolled up to all capacitor-bearing components in an assembly, to evidence ESG claims about tantalum in an assembled device. The BOM of a production run for a component could be sourced from multiple suppliers, the components of an assembly could be sourced from different suppliers; the device seller needs to roll that all up.

**Comment by ReLOG3PSNE** [comment]
Team, I personally agree with @monkeypants, in the sense that:

1. post/ pre points as relative matter, thus I would rather see UNTP to look at the whole continuum (and so the EU... and than the consequent coordination work between them that @onthebreeze  already mentioned to All of us that has started some months ago)
2. no upwards/downwards limits for the UNTP within EACH supply chain. The way I see (without, as mentioned at the very beginning, the willingness to pull a kind of (irrealistic) "magic wand that fix everything everywhere") is that the UNTP will work on the 80-20 side: the alignment with UNTP will cover the 80% of the (high-level) cases of transparency rules, where the remaining 20% will be derived, specifically in whithin each supply chain domain (and further sub-domains).

I am convinced that this anyhow is how @onthebreeze and All of the Team has been working to set since the commencement of our venture.

**Comment by nissimsan** [comment]
If we do support the post-sales "down stream", how and where does data get stored?

**Comment by nissimsan** [comment]
IMO to close this issue, we need a solution proposed on how to technically solution the downstream additions (repairs, resell, etc)

**Comment by nissimsan** [comment]
![image](https://github.com/uncefact/spec-untp/assets/34443212/cff23e9e-a299-4ae8-983e-680501962cbc)

**Comment by nissimsan** [comment]
I was wrong to introduce "downstream" into this ticket. Let's close and continue that conversation on a dedicated issue.

**Comment by nissimsan** [comment]
Conclusion on the meeting: There is no reason for this group to set (upstream) depth limits on the links of the chain. There should be market incentives to drive further backwards.
