### ISSUE TITLE
Digital Product Passport Sample File

### ISSUE THREAD

**Issue by mxshea** [uncefact/spec-untp#30]
In the DPP Sample File code, the Credential Status section refers to revocation-list-2020.

"credentialStatus": {
    "id": "https://api.vckit.showthething.com/credentials/status/revocation-list-2020/did_web_processor.agtrace.showthething.com/66",
    "type": "BitstringStatusListEntry",
    "revocationListIndex": 4,
    "revocationListCredential": "https://api.vckit.showthething.com/credentials/status/revocation-list-2020/did_web_processor.agtrace.showthething.com/66"
  },

Should this be updated?

**Comment by onthebreeze** [comment]
Yes - it should reference https://www.w3.org/TR/vc-bitstring-status-list/  as per https://uncefact.github.io/spec-untp/docs/specification/VerifiableCredentials - but that sample file is created by open source VCkit implementation and will get updated every time we update the DPP data model.  Might be better to update the implementation itself so that next time we generate a credential it has the right status method.

**Comment by zachzeus** [comment]
Get one from our Ag pilot and publish it here.

**Comment by onthebreeze** [comment]
Agree -all samples should reflect VCDM 2.0 and bistring status list.
