### ISSUE TITLE
Provide a pattern for enabling suppliers to use the best information they can for the products they are supplying

### ISSUE THREAD

**Issue by zachzeus** [uncefact/spec-untp#44]
Evidence to support claims in a product passport (or other contracts for sale, etc #43 ) must be available at the time the claims are made. Some types of evidence (e.g. audited/certified records) could be retrospective, and not be available at the point of sale/negotiation, but may be available later in the trade transaction lifecycle. For example; negotiation (prior to transaction), sale (initial transaction), and downstream in the supply chain. Given that different types of evidence are available at different times, how can a buyer use the best information available to set price on ESG values evidenced in the digital supply chain?

**Comment by monkeypants** [comment]
I think this is about ConformityCredentials; As the model is currently drawn:
* a ConformityAttestation has a collection of ConformityAssessments.
* each ConformityAssessment has a reference (type StandardOrRegulation),
* The StandardOrRegulation could define how how the ConformityMetrics are calculated

So, the question of "best information available" really comes down to the ConformityAssessments based on the evidence to hand. At a different point in time, when more evidence is available, additional ConformityAssessments might be possible.

It's really buyer's policy to decide how to price different ConformityAssessments, based on their values and the values downstream in their supply chain.

**Comment by monkeypants** [comment]
Hmm, I think the ConformityEvidence and associated EvidenceFile might need more properties, to manage the temporal ranges. For example, imagine some StandardOrRegulation that stipulates a heuristic for calculating the ConformityMetric.

* where high-integrity, audited, accredited data exists, use it.
* if there is a gap in coverage of the high-integrity data, use an estimate based on industry averages
* if the high-integrity data does not cover 90% of the time period of assessment (e.g. lifecycle of input), do not produce a score - valid scores must have at least 90% high-integrity data
* produce a  ConformityMetric called "score" that is a weighted sum of the industry average + high-integrity data
* produce a ConformityMetric called "confidence" that is the proportion of the score based on high-integrity data

That's a plausible heuristic for combining different kinds of evidence into a score. It's just an example of "plausible heuristics", and really it's up to markets and regulators to decide what heuristics are fit for purpose. But the point is:

* there may be multiple ConformityAssessments under the same ConformityAttestation.
* the StandardOrRegulation have a value that is determined by the market
* We need temporal scope associated with ConformityEvidence.

Currently, ConformityEvidence has multiple EvidenceFiles. If it stays that way, then we probably needs an (optional) temporal scope properties; e.g. `date_from` and `date_until` on EvidenceFile. Another way to do it would be to make the relationship between ConformityAssessment:ConformityEvidence into 1:N  (rather than 1:1 as it is now), in which case the ConformityEvidence would be the place for the temporal scope attributes.

**Comment by zachzeus** [comment]
@monkeypants How would a verifier or customer know to combine heuristics?

**Comment by monkeypants** [comment]
I suppose they will do it in the way that grinds least against their beliefs, or best advantages their negotiations :)

The market will have to assess how it values the heuristics. In some pockets a regulator or industry group may settle on a standard. It' should swim upstream from the "regulated consumer" end of the supply chain.

Quite possibly, some bespoke heuristics may achieve premium prices because of perceived integrity, superior oversight/intelligence, historic performance, etc.
