### ISSUE TITLE
Product image

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#49]
The notion of a single product image may or may not be sufficient for the DPP. Typically, products have multiple images but even if there's only one, 'an image' often comes with other info. See, for example, the [schema.org Image Object](https://schema.org/ImageObject) for which GS1 defines a subclass https://www.gs1.org/voc/ReferencedFileDetails.

**Comment by onthebreeze** [comment]
Yes, good point.  Begs a bigger question about schema.org alignment.  I notice that the schema.org ImageObject has over 200 properties (many inherited from parent classes like CreativeWork.  It includes at least 3 seemingly equivalent ways to specify the actual image URL.  

I think we should "tag" our model with schema.org definitions - so that, where possible, the JSON-LD @context file references a schema.org property.  But I'm not sure we should just use the schema.org objects as the DPP will explode to become impossibly complex.  

THoughts?

**Comment by philarcher** [comment]
We struggle with this a little. There are good reasons to use schema.org when possible but if the use case needs precise semantics than schema.org is not the right choice. In our vocab we make use of the SKOS relationships to link the GS1 term to its nearest or actual equivalent term. See https://www.gs1.org/voc/Product for example. That looks like the right kind of semantic alignment for the UN DPP as you suggest. That said, we're delighted when schema.org adopts our terms as they have, pretty much wholesale, for https://www.gs1.org/voc/CertificationDetails (https://schema.org/Certification)

**Comment by onthebreeze** [comment]
Make it an array of links.  With 
 - image URL
 - altText
 - caption (IP rights if applicable)

**Comment by onthebreeze** [comment]
Image is now a simple `Link` object.  Not nearly as rich as the schema.org version but hopefully just good enough.
