### ISSUE TITLE
ManufacturedDate Definition

### ISSUE THREAD

**Issue by GerhardHNL** [uncefact/spec-untp#73]
It is now: The ISO 8601 date on which the product batch was manufactured.

Suggestion either to use names like: Batch Production Date or Batch Manufacture Date.

It is about the Batch.

In other definitions where manufactured is used in attribute name we could write "manufactured or produced" to align with terms in other industries, like agriculture.

**Comment by onthebreeze** [comment]
First I think we all agree that productionDate (or other preferred name) only applies to serialised items or batches and not for product class (for which a productionDate is meaningless).

My understanding is that some production processes can produce serialised items without any sense of a batch - because they are made on continuous production lines and there is just no concept of a batch.  In that case would it be confusing to rename this as BatchProductionDate ?

**Comment by onthebreeze** [comment]
Modified the definition to read "The ISO 8601 date on which the product batch or individual serialised item was manufactured."  Maybe that clarifies that this data could refer either to the batch production date or the item production date (for things that arent made in batches).
