### ISSUE TITLE
explore GS1 CertificationDetails (logical combinations of certificationSubjects)

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-untp#83]
@nissimsan @zachzeus @onthebreeze 

EPCIS events can mention https://ref.gs1.org/epcis/certificationInfo.
That points to https://www.gs1.org/voc/CertificationDetails, which is not much compared to your DPP+VC model...
Except for https://www.gs1.org/voc/certificationSubject, which represents somewhat complex combinations of subjects that are certified.

Thinking of #82 , it allows you to express statements like
- Pete's Meats is allowed to process Beef or Pork at its facilities Pete's Plant 123 or Pete's Plant 456.
- Pete's Meats is certified that it doesn't cause deforestation when processing Beef at its facility Pete's Plant 123

And an example of a negative:
- However Mike's Beef is also a tenant at a part of Pete's Plant 123, and it doesn't use any deforestation measures, so is not certified

(Of course, this is Closed World, so if we don't have another certificate about Mike's, we can assume he doesn't use deforestation measures)

**Comment by VladimirAlexiev** [comment]
From a pointer by @GerhardHNL, I found [unece:SpecifiedCertification](https://vocabulary.uncefact.org/SpecifiedCertification).
I thas some elements in common with [gs1:CertificationDetails](https://www.gs1.org/voc/CertificationDetails), but I don't understand how can one specify the party or product that's certified?
- there is the child (subobject) class [unece:Assertion](https://vocabulary.uncefact.org/Assertion), but it doesn't specify party or product either
- there is [unece:relatedLocation](https://vocabulary.uncefact.org/relatedLocation) that links to unece:Location, which itself relates to GLN and [unece:ProductionUnit](https://vocabulary.uncefact.org/ProductionUnit), so that is covered

**Comment by GerhardHNL** [comment]
Dear Vladimir,

 

Thanks for your questions. 

 

Answers:

In short: the vocabulary on Github is a subset of the UNCCL (base library). The information you want is available but marked as not used in our modelling tool. Certification is seen as a process at UN/CEFACT.

More detailed: see below 

 

UN/CEFACT:

Specified Certification:  is the process of certifying that a certain product, process or organization has passed performance tests, or qualification requirements stipulated in a standard or regulation.

 

In practice, certification can refer to both a process and a document, depending on the context in which it is use, but not according to its present UN/CEFACT definition. The base class “certification” did already exist since 2010 (D10A) and in 2021 (D22A) the generic business information class ‘specified certification’ was created on top of it. All to accommodate the Blockchain Pilot for textiles. Because at that time (2021) the GS1 EPCIS was not yet ratified, we did make the full version of this Specified Certification available for BSP/textile context, see here  

https://service.unece.org/trade/uncefact/publication/Agriculture/TTTL-TraceabilityEventMessage/HTML/001.htm 

 

You might have noticed that the ‘specified certification’ class has an association to ‘related referenced standard’ class. The ‘referenced standard’ has a lot optional attributes and associations. Also, towards specific documents (as a result of the certification process). The UNCEFACT Product Conformity project resulted in more alignment with ISO standards (CASCO). Therefore, new classes will be submitted, such as conformity assessment and conformity attestation. The latter could be a class being associated with ‘referenced standard’ in ‘specified certification’, by this becoming flexible for all types of attestations being a result of an assessment, such as a certification. The class attestation will have attributes such as issuer and issued to. The precent ‘Specified Certificate’ in Referenced Standard has ‘Certified Party’ and ‘Issuer Party’ available, if needed.

 

Specified certification is available on product level, within the class TT_ Product (although only used in the context of Animal Traceability <https://unece.org/fileadmin/DAM/uncefact/BRS/BRS_Animal_Traceability_BRS_v1.2.pdf> . So not activated in BSP/Textiles TT events model.  For the assertion there is an attribute available named: Sustainability_ Assertion. Issuing Party_ Identification. Identifier. As Specified Certification is part of several event types, see further below, the destination and source party are available for each event type. But, of course, certification is meant to be process information, for which now only the URI might give more details (looking at its present restricted BSP version). Since 2017, UN/CEFACT worked on the EPCIS standard, but in the context of Animal Traceability <https://unece.org/fileadmin/DAM/uncefact/BRS/BRS_Animal_Traceability_BRS_v1.2.pdf> , that’s why you will find in base library (UNCCL <https://unece.org/trade/documents/2024/01/reports/unccl-version-23b> ) more traceability components then used in textiles <https://unece.org/sites/default/files/2021-03/BRS-Traceability-Transparency-TextileLeather-Part2-UC_CCBDA_v1.pdf> . On Github you will only find a subset (BSP) of our base library (UNCCL <https://unece.org/trade/documents/2024/01/reports/unccl-version-23b> ). As mentioned, BSP and ‘snapshots’ exports on Github, contain restrictions on our base classes. On Github we published the JSON syntax. On the UNCEFACT pages we published XML variants <https://unece.org/trade/uncefact/mainstandards> . When data is available in the UNCCL, it is the head of business community to release an existing attribute or association to be used in a particular context, such as BSP. The class Trade_ Party and Trade_ Product do have Specified_ Certification as an association, but within TT_ Events we used TT_ Party and, for animal traceability, TT_ Product, which do not have Specified_ Certification as an association. We want to stick close to ISO/GS1 Traceability classes. New classes, such as for IOT (sensors) were still at that time in review. These could be added in new submission cycle (end of this year). We based in the past our traceability standard 1.2 and not 2.0 (JSON and IOT etc variant).

 

I hope this answers your questions.  

 



 

Textile subset for Traceability event data



 

 

tFrom: Vladimir Alexiev ***@***.***> 
Sent: woensdag 3 juli 2024 12:35
To: uncefact/spec-untp ***@***.***>
Cc: GerhardHNL ***@***.***>; Mention ***@***.***>
Subject: Re: [uncefact/spec-untp] explore GS1 CertificationDetails (logical combinations of certificationSubjects) (Issue #83)

 

From a pointer by @GerhardHNL <https://github.com/GerhardHNL> , I found unece:SpecifiedCertification <https://vocabulary.uncefact.org/SpecifiedCertification> .
I thas some elements in common with gs1:CertificationDetails <https://www.gs1.org/voc/CertificationDetails> , but I don't understand how can one specify the party or product that's certified?

*	there is the child (subobject) class unece:Assertion <https://vocabulary.uncefact.org/Assertion> , but it doesn't specify party or product either
*	there is unece:relatedLocation <https://vocabulary.uncefact.org/relatedLocation>  that links to unece:Location, which itself relates to GLN and unece:ProductionUnit <https://vocabulary.uncefact.org/ProductionUnit> , so that is covered

**Comment by VladimirAlexiev** [comment]
More details in https://github.com/schemaorg/schemaorg/issues/3564

**Comment by onthebreeze** [comment]
We had to make a choice about whether to use the certification scheme in traceability events or to use the separate product conformity model defined by UN/CEFACT in https://unece.org/trade/documents/2024/07/session-documents/brs-digital-product-conformity-certificate-exchange-high 

That UN project had significant expert representation from conformity subject matter experts around the world and is a formal UN standard.  As you point out it is also richer than the EPCIS link.  

To avoid confusion about how and where to specify conformity / certification, UNTP has dropped the EPCIS reference in favour of the DigitalConformityCredential.
